name: simple_example
description: A simple example showcasing go_router_guards main use cases
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.5
  go_router_guards:
    path: ../
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  go_router_builder: ^4.1.0
