name: go_router_guards_example
description: Example app demonstrating go_router_guards usage
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router:
    git:
      url: https://github.com/tomassasovsky/packages.git
      ref: feat/go-router-context-redirect
      path: packages/go_router
  go_router_guards:
    path: ../packages/go_router_guards
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^3.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
