version: "3.9"

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-router-guards-docs:latest
    ports:
      - "4321:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
