name: publish/route_guards

on:
  push:
    tags:
      - "route_guards-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    environment: pub.dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 📦 Publish
        uses: ./.github/actions/pub_publish
        with:
          working_directory: packages/route_guards
